### ISSUE TITLE
tauri::Builder::any_thread does not exist on macOS: add a platform-split test builder

### ISSUE THREAD

**Issue by mblua** [mblua/AgentsCommander#1378]
Part of epic #1113.

## Situation

`tauri::Builder::any_thread` is declared `#[cfg(any(windows, target_os = "linux"))]` (vendored `tauri-2.10.3/src/app.rs:1503`). Test code calls it unconditionally, so on macOS `cargo check --all-targets` fails with:

```
error[E0599]: no method named `any_thread` found for struct `tauri::Builder<R>` in the current scope
```

This is the failure blocking the new `rust-regression-macos` gate added by #1154 / PR #1156. It fails at `cargo check`, before clippy even runs.

## Why

The epic never anticipated macOS: its completion gate runs on the host (Windows), where `any_thread` exists.

## Change

Add `src-tauri/src/test_support.rs` exposing a `pub fn test_builder()` with two platform-split definitions (two whole function bodies, not one body with an internal `#[cfg] let`, which would trip `clippy::let_and_return` on macOS). Register it as `pub mod test_support;` in `lib.rs` and rewrite the call sites to use it. It must be `pub` rather than `#[cfg(test)]` because integration-test crates are separate crates and cannot see a library's `#[cfg(test)]` items.

Accepted consequence: on macOS the builder is not `any_thread`, so such a test would panic at run time there. Tauri offers no macOS alternative and neither new gate runs `cargo test`, so the fix is compile-only. Adding macOS test execution is a separate issue.

Being implemented as part of PR #1156 (see `plans/1154-nonwindows-rust-gate-failures.md`).

**Comment by mblua** [comment]
Scope decision (2026-08-15): this child is being implemented inside **PR #1156** (branch `ci/1154-nonwindows-rust-gates`, issue #1154) instead of its own branch.

Reason: #1154 adds the `rust-regression-linux` and `rust-regression-macos` PR gates, and those gates stay red until every remaining #1113 child is fixed. Splitting them across separate PRs would leave #1156 red until the last one landed.

Certified plan: `plans/1154-nonwindows-rust-gate-failures.md` (gitignored; also carried in the PR). The epic #1113 checklist records the same waiver. This issue will be closed by PR #1156.
